name: wkt_parser
description: Wkt-parser-dart is a Dart version of proj4js/wkt-parser.
version: 1.0.3
homepage: https://github.com/fegyi001/wkt-parser-dart

environment:
  sdk: ">=2.7.0 <3.0.0"

# dependencies:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.12.0
